version: 2.1

orbs:
  aws-cli: circleci/aws-cli@2.0.3  
  aws-eks: circleci/aws-eks@2.2.0  
  kubernetes: circleci/kubernetes@0.4.0

jobs:
  setup-run-lint:
    docker:
      - image: circleci/node:13.8.0
    working_directory: ~/app
    steps:
      - checkout
      - run:
          name: install dependenices and run linting for blue app
          command: |
            cd blue
            make install
            make lint

      - run:
          name: install dependenices and run linting for green app
          command: |
            cd green
            make install
            make lint
  
  build-docker-images:
    docker:
      - image: circleci/node:13.8.0
    working_directory: ~/app
    steps:
      - checkout
      - setup_remote_docker:
          docker_layer_caching: true
      - run:
          name: Build blue_app container
          command: |
            cd blue
            docker build -t capstone_blueapp .
            ./upload_docker.sh "$DOCKERHUB_PASSWORD"

      - run:
          name: Build green_app container
          command: |
            cd green
            docker build -t capstone_greenapp .
            ./upload_docker.sh "$DOCKERHUB_PASSWORD"
 
  create-eks-cluster:
      docker:
        - image: circleci/node:13.8.0
      parameters:
        cluster-name:
          description: |
            Name of the EKS cluster
          type: string
      steps:
        - checkout
        - run:
            name: Install the eksctl tool
            command: |
              if which eksctl > /dev/null; then
                echo "eksctl is already installed"
                exit 0
              fi
              mkdir -p eksctl_download
              curl --silent --location --retry 5 "https://github.com/weaveworks/eksctl/releases/latest/download/eksctl_$(uname -s)_amd64.tar.gz" \
                | tar xz -C eksctl_download
              chmod +x eksctl_download/eksctl
              SUDO=""
              if [ $(id -u) -ne 0 ] && which sudo > /dev/null ; then
                SUDO="sudo"
              fi
              $SUDO mv eksctl_download/eksctl /usr/local/bin/
              rmdir eksctl_download
        - aws-eks/create-cluster:
            cluster-name: << parameters.cluster-name >>

workflows:
  default:
    jobs:
      - setup-run-lint
      - build-docker-images:
          requires:
            - setup-run-lint
      - create-eks-cluster:
              cluster-name: capstone-deploy
              requires:
                - build-docker-images