version: 2.1

orbs:
  aws-cli: circleci/aws-cli@2.0.3  
  aws-eks: circleci/aws-eks@2.2.0  
  kubernetes: circleci/kubernetes@0.4.0

jobs:
  setup-run-lint:
    docker:
      - image: circleci/node:13.8.0
    working_directory: ~/app
    steps:
      - checkout
      - run:
          name: install dependenices and run linting for blue app
          command: |
            cd blue
            make install
            make lint

      - run:
          name: install dependenices and run linting for green app
          command: |
            cd green
            make install
            make lint
  
  build-docker-images:
    docker:
      - image: circleci/node:13.8.0
    working_directory: ~/app
    steps:
      - checkout
      - setup_remote_docker:
          docker_layer_caching: true
      - run:
          name: Build blue_app container
          command: |
            cd blue
            docker build -t capstone_blueapp .
            ./upload_docker.sh "$DOCKERHUB_PASSWORD"

      - run:
          name: Build green_app container
          command: |
            cd green
            docker build -t capstone_greenapp .
            ./upload_docker.sh "$DOCKERHUB_PASSWORD"

workflows:
  default:
    jobs:
      - setup-run-lint
      - build-docker-images:
          requires:
            - setup-run-lint